#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width                2
bspc config window_gap                  10

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config border_radius               20

bspc config focus_follows_pointer       true
bspc config single_monocle              true
bspc config focused_border_color        \#FEFEFE
bspc config normal_border_color         \#111824
bspc config click_to_focus              true


#bspc config pointer_modifier            control
#bspc config pointer_action1             move
#bspc config pointer_action2             resize_sidie
